version: '3'
services:
#mssql docker
  rentacar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - rentacarnet

  rent_a_car-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:RentACar=Server=rentacar-sql,1433;Database=170044;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 51886:80
    networks:
      - rentacarnet      
    links:
      - rentacar-sql
    depends_on:
      - rentacar-sql
    image: billings-docker:latest

networks:
  rentacarnet:
    driver: bridge       